2024-10-31 23:50:43,879 - root - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\kiril.KURILL\PycharmProjects\Module1\module_10-14\tests_12_4.py", line 71, in test_run
    runner = Runner(5)
             ^^^^^^^^^
  File "C:\Users\kiril.KURILL\PycharmProjects\Module1\module_10-14\tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-31 23:50:43,880 - root - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\kiril.KURILL\PycharmProjects\Module1\module_10-14\tests_12_4.py", line 61, in test_walk
    runner = Runner("Runner", speed=-1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kiril.KURILL\PycharmProjects\Module1\module_10-14\tests_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
